<?php

header('Content-Type: text/json');

print "
	[
	        {id:'AL', name:'Alabama', nickname:'The Heart of Dixie'},
	        {id:'AK', name:'Alaska', nickname:'The Land of the Midnight Sun'},
	        {id:'AZ', name:'Arizona', nickname:'The Grand Canyon State'},
	        {id:'AR', name:'Arkansas', nickname:'The Natural State'},
	        {id:'CA', name:'California', nickname:'The Golden State'},
	        {id:'CO', name:'Colorado', nickname:'The Mountain State'},
	        {id:'CT', name:'Connecticut', nickname:'The Constitution State'},
	        {id:'DE', name:'Delaware', nickname:'The First State'},
	        {id:'DC', name:'District of Columbia', nickname:\"The Nation's Capital\"},
	        {id:'FL', name:'Florida', nickname:'The Sunshine State'},
	        {id:'GA', name:'Georgia', nickname:'The Peach State'},
	        {id:'HI', name:'Hawaii', nickname:'The Aloha State'},
	        {id:'ID', name:'Idaho', nickname:'Famous Potatoes'},
	        {id:'IL', name:'Illinois', nickname:'The Prairie State'},
	        {id:'IN', name:'Indiana', nickname:'The Hospitality State'},
	        {id:'IA', name:'Iowa', nickname:'The Corn State'},
	        {id:'KS', name:'Kansas', nickname:'The Sunflower State'},
	        {id:'KY', name:'Kentucky', nickname:'The Bluegrass State'},
	        {id:'LA', name:'Louisiana', nickname:'The Bayou State'},
	        {id:'ME', name:'Maine', nickname:'The Pine Tree State'},
	        {id:'MD', name:'Maryland', nickname:'Chesapeake State'},
	        {id:'MA', name:'Massachusetts', nickname:'The Spirit of America'},
	        {id:'MI', name:'Michigan', nickname:'Great Lakes State'},
	        {id:'MN', name:'Minnesota', nickname:'North Star State'},
	        {id:'MS', name:'Mississippi', nickname:'Magnolia State'},
	        {id:'MO', name:'Missouri', nickname:'Show Me State'},
	        {id:'MT', name:'Montana', nickname:'Big Sky Country'},
	        {id:'NE', name:'Nebraska', nickname:'Beef State'},
	        {id:'NV', name:'Nevada', nickname:'Silver State'},
	        {id:'NH', name:'New Hampshire', nickname:'Granite State'},
	        {id:'NJ', name:'New Jersey', nickname:'Garden State'},
	        {id:'NM', name:'New Mexico', nickname:'Land of Enchantment'},
	        {id:'NY', name:'New York', nickname:'Empire State'},
	        {id:'NC', name:'North Carolina', nickname:'First in Freedom'},
	        {id:'ND', name:'North Dakota', nickname:'Peace Garden State'},
	        {id:'OH', name:'Ohio', nickname:'The Heart of it All'},
	        {id:'OK', name:'Oklahoma', nickname:'Oklahoma is OK'},
	        {id:'OR', name:'Oregon', nickname:'Pacific Wonderland'},
	        {id:'PA', name:'Pennsylvania', nickname:'Keystone State'},
	        {id:'RI', name:'Rhode Island', nickname:'Ocean State'},
	        {id:'SC', name:'South Carolina', nickname:'Nothing Could be Finer'},
	        {id:'SD', name:'South Dakota', nickname:'Great Faces, Great Places'},
	        {id:'TN', name:'Tennessee', nickname:'Volunteer State'},
	        {id:'TX', name:'Texas', nickname:'Lone Star State'},
	        {id:'UT', name:'Utah', nickname:'Salt Lake State'},
	        {id:'VT', name:'Vermont', nickname:'Green Mountain State'},
	        {id:'VA', name:'Virginia', nickname:'Mother of States'},
	        {id:'WA', name:'Washington', nickname:'Green Tree State'},
	        {id:'WV', name:'West Virginia', nickname:'Mountain State'},
	        {id:'WI', name:'Wisconsin', nickname:\"America's Dairyland\"},
	        {id:'WY', name:'Wyoming', nickname:'Like No Place on Earth'}
	    ]
";

?>