<?php
namespace Phpdocx\Factory;
use Phpdocx\Create\CreateDocx;
/**
 * Class to use PHPDocX within a namespace
 *
 * @category   Phpdocx
 * @package    factory
 * @copyright  Copyright (c) Narcea Producciones Multimedia S.L.
 *             (http://www.2mdc.com)
 * @license    http://www.phpdocx.com/wp-content/themes/lightword/pro_license.php
 * @version    2014.04.09
 * @link       http://www.phpdocx.com
 */


class Phpdocx_Phpdocx extends CreateDocx
{
    
}
